[project]
name = "robotframework-dosomething"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Biehl", email = "dbiehl@live.de" },
    { name = "Florian Kromer", email = "kromer-florian@protonmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Framework :: Robot Framework :: Library"
]
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.2.2",
]

# https://docs.astral.sh/ruff/configuration/
[tool.ruff.lint]
extend-select = ["I"]

# https://github.com/jendrikseipp/vulture?tab=readme-ov-file#configuration
[tool.vulture]
min_confidence = 100
paths = ["src"]

# https://deptry.com/usage/#configuration
[tool.deptry.per_rule_ignores]
DEP002 = ["robotframework"]

# https://docs.pytest.org/en/7.1.x/reference/reference.html#ini-options-ref
[tool.pytest.ini_options]
testpaths = ["utests"]

# https://robotcode.io/03_reference/config
[tool.robot]
paths = ["atests"]
[tool.robot.variables]
MY_VAR = "Hello, World!"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/DoSomething"]

[dependency-groups]
dev = [
    "deptry>=0.23.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "robotcode[runner]>=1.0.3",
    "robotframework-tidy>=4.16.0",
    "ruff>=0.11.7",
]
